# Generated by Django 5.0 on 2026-02-05 22:36

import modelos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_de_modelo', models.CharField(max_length=50)),
                ('fecha_de_inicio', models.DateField(auto_now_add=True)),
                ('segmentos', models.CharField(choices=[('VANS', 'Utilitario'), ('CAMIONES', 'Pesados'), ('BUSES', 'Colectivos')], max_length=50)),
                ('code', models.CharField(default=modelos.models.generar_code, max_length=32, unique=True)),
            ],
        ),
    ]
