# Generated by Django 5.0 on 2026-01-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelo',
            old_name='apellido',
            new_name='tipo_de_modelo',
        ),
        migrations.AlterField(
            model_name='modelo',
            name='segmentos',
            field=models.CharField(choices=[('VANS', 'Utilitario'), ('CAMIONES', 'Pesados'), ('BUSES', 'Colectivos')], max_length=50),
        ),
    ]
